### ISSUE TITLE
divergence float FPU

### ISSUE THREAD

**Issue by lfernand4** [pulp-platform/pulpissimo#16]
I run this short C code with RISCY, RISCY+FPU and GCC : 
![image](https://user-images.githubusercontent.com/36438648/40608412-b2fa8fa6-626b-11e8-92d3-17f614cd37c3.png)
Result with GCC and RISCY (No FPU) : 
![image](https://user-images.githubusercontent.com/36438648/40608443-d14f6558-626b-11e8-8ba4-3177102f89e8.png)
Result with RISCY+FPU : 
![image](https://user-images.githubusercontent.com/36438648/40608455-ddf4049e-626b-11e8-99c6-588cb1bd2525.png)

Can you explain to me this error with the FPU ?

**Comment by FrancescoConti** [comment]
I think maybe @stmach can help you

**Comment by stmach** [comment]
Hi! Thank you for raising an issue.
What platform (rtl simulation, virtual platform) do you use to run the program?
There seems to be a mismatch between the program or model depending on whether FP emulation in software is done or not.
What strikes me as interesting is that the output of the second code contains values like `46.99999936` which is not a value that can be represented in single-precision floating-point.
I see following factors that could play a role in this issue:
- You use a custom print function for floats where potentially some implicit cast to `double` could happen
- The initialization of your vectors is done by implicit casts from `int`
- If you enable hardware-floats, the compiler might do be trying to optimize the code and add some static initialization using `double`

In order to try to figure out the source of the issue, please try the following and report any interesting findings:
- Change initialization to explicitly assign `float` values instead of integers in the `generateur` function
- Try using `printf` with the `%f` switch to print float values (if supported by the runtime). However printf's %f switch operates on doubles so we might see wrong values here too.
- Print out the bit-patterns of your vector to see what's actually stored in there, by getting the patterns trough the hacky '*(int *) &x[n]` cast on the vector elements

**Comment by lfernand4** [comment]
I run program with the RTL simulation platform.
Explicitly assign float values : Same Issue
printf with the %f : 
![image](https://user-images.githubusercontent.com/36438648/40717215-d770d95c-640b-11e8-9bab-3eeada497211.png)
Print out the bit-patterns : 
![image](https://user-images.githubusercontent.com/36438648/40717231-e0985708-640b-11e8-9c2e-b34df5615bfe.png)

**Comment by stmach** [comment]
Looking at the bit patterns (easier seen when looked at in hexadecimal), the correct representation of the floats are actually stored in the variable.
Thus the error likely lies in the `printfloat` function. Be aware that you are trying to print out single-precision floating-point values with 10 digits of accuracy while single-precision floats only give you around 7 usable decimal digits of accuracy. I don't know where exactly the error gets in but it might be the compiler that statically inserts some double precision values because you seem to need more precision than float offers.
Try debugging your print function by printing the intermediate values it computes when printing the float value 47.0 for example and see at which point you don't receive the expected output.

**Comment by lfernand4** [comment]
And why can't I use printf with %f ?

**Comment by stmach** [comment]
Likely the version of printf in the runtime does not include the %f flag.
Pinging @haugoug, we will know.

**Comment by lfernand4** [comment]
Thank you for all those informations
