### ISSUE TITLE
Mapping Error in DC

### ISSUE THREAD

**Issue by Ahmedsaied9** [pulp-platform/pulpissimo#335]
When running Compile command in DC i get this error.

 
![image](https://user-images.githubusercontent.com/88512981/165758971-f8b16cae-9dd3-49b0-a8ad-dab70f88382a.png)

any clue how to solve this?

**Comment by christian-lanius** [comment]
The FLL in general can not be synthesized as far as I am aware, if you check @meggiman comment on doing an ASIC implementation here in #292. The digital part should be synthesizable though, so keep that in mind.
In this specific case, the SelB_SP register is an asynchronous reset, falling edge sensitive flipflop. If your library does not have such a register, you might observe this error.  One possible fix would be to manually instantiate an inverter cell in the clock path and then use a rising edge FF.
You can instruct DC to do this automatically (according to the internet), if you check this comment [here](http://jks.tech/?kb=error-the-register-is-not-mapped-because-ofa-lack-of-compatible-library-cells-with-correct-clockenable-phase-opt-1217):

>If you want  to allow mapping to a library register with the opposite clock/enable phase,  then you  can use the variable  compile_automatic_clock_phase_inference  to alter  the way that mapping operates. Setting this variable to “none” will instruct the tool to ignore clock phase and allow  mapping to registers with both positive and negative clock/enable phase as needed.  Setting this variable to “relaxed”  will instruct the tool to only try the opposite phase device if there is no other way to implement the register with the automatically  inferred phase.   And,  setting the  variable to “strict” (the default setting) will instruct the tool to reject all library cells whose clock/enable phase does not match  the automatically  inferred phase.
